---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chocolatyarenaappdeployment
spec:
  replicas: 1
  strategy: 
    type: Recreate
  selector: 
    matchLabels: 
      app: chocolatyarenaapp
  template:
    metadata:
      labels:
        app: chocolatyarenaapp	 
      name: chocolatyarenaapppod
    spec: 
      containers:
      - name: chocolatyarenaappcontainer
        image: chocolatyarena/chocolatyarenaapp:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: chocolatyarenaappsvc
spec:
  type: LoadBalancer
  selector:
    app: chocolatyarenaapp
  ports:
  - port: 80
    targetPort: 80
...