---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chocolatyarenaappdeployment
spec:
  replicas: 2
  strategy: 
      type: Recreate
  selector: 
    matchLabels: 
      app: chocolatyarenaapp
  template:
    metadata:
    name: chocolatyarenaapppod
    labels:
      app: chocolatyarenaapp	 
    spec: 
      containers:
      - name: chocolatyarenaappcontainer
        image: chocolatyarena/chocolaty-arena-web:v3
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: chocolatyarenaappsvc
  spec:
    type: LoadBalancer
    selector:
    app: chocolatyarenaapp
    ports:
    - port: 80
      targetPort: 8080
...